import nodeJs from './images/courses/node-js.webp'
import npm from './images/courses/npm.webp'
import php from './images/courses/php-projects.webp'
import typeScript from './images/courses/type-script.webp'
import python from './images/courses/python.webp'
import css from './images/courses/css.webp'
import vue from './images/courses/vue-js.webp'
import html from './images/courses/html.webp'
import django from './images/courses/django.webp'
import github from './images/courses/github.webp'
import webSocket from './images/courses/web-socket.webp'
import jsBlack from './images/courses/js-black.webp'
import vsCode from './images/courses/vs-code.webp'
import apiNodeJs from './images/courses/api-node-js.webp'
import nextJs from './images/courses/next-js.webp'
import chatGpt from './images/courses/chat-gpt.webp'
import reactJs from './images/courses/react-js.webp'
import fastHtmlCss from './images/courses/fast-html-css.webp'


export const courses = [
  {
    courseId: 0,
    lastUpdate: "2023-06-14T05:34:42.901Z",
    tumbImageAddress: nodeJs,
    likeCount: 66,
    title: "متخصص NodeJS",
    currentRegistrants: 69,
    statusName: "درحال ثبت نام",
    teacherName: "آرمان رضوانی",
    levelName: "پیشرفته",
    cost: 369_000,
    courseRate: 4,
    currentRate: 3,
    technologyList: "BackEnd",
  },
  {
    courseId: 1,
    lastUpdate: "2024-02-16T05:34:42.901Z",
    tumbImageAddress: npm,
    likeCount: 41,
    title: "آموزش NPM",
    currentRegistrants: 20,
    statusName: "درحال ثبت نام",
    teacherName: "امیرعباس بابائی",
    levelName: "مبتدی",
    cost: 400_000,
    courseRate: 2,
    currentRate: 4,
    technologyList: "JavaScript",
  },
  {
    courseId: 2,
    lastUpdate: "2024-01-11T05:34:42.901Z",
    tumbImageAddress: php,
    likeCount: 12,
    title: "پروژه های کاربردی PHP",
    currentRegistrants: 44,
    statusName: "درحال ثبت نام",
    teacherName: "آرمان رضوانی",
    levelName: "پیشرفته",
    cost: 666_000,
    courseRate: 5,
    currentRate: 4,
    technologyList: "BackEnd",
  },
  {
    courseId: 3,
    lastUpdate: "2023-11-11T05:34:42.901Z",
    tumbImageAddress: reactJs,
    likeCount: 255,
    title: "آموزش ReactJS",
    currentRegistrants: 343,
    statusName: "درحال ثبت نام",
    teacherName: "آرمان رضوانی",
    levelName: "پیشرفته",
    cost: 1_500_000,
    courseRate: 5,
    currentRate: 4,
    technologyList: "FrontEnd",
  },
  {
    courseId: 4,
    lastUpdate: "2023-04-04T05:34:42.901Z",
    tumbImageAddress: github,
    likeCount: 258,
    title: "آموزش Git & Github",
    currentRegistrants: 444,
    statusName: "درحال ثبت نام",
    teacherName: "آرمان رضوانی",
    levelName: "پیشرفته",
    cost: 250_000,
    courseRate: 5,
    currentRate: 4,
    technologyList: "Soft Skill",
  },
  {
    courseId: 5,
    lastUpdate: "2023-08-22T05:34:42.901Z",
    tumbImageAddress: vue,
    likeCount: 73,
    title: "آموزش VueJS",
    currentRegistrants: 111,
    statusName: "درحال ثبت نام",
    teacherName: "امیرعباس بابائی",
    levelName: "مقدماتی",
    cost: 330_000,
    courseRate: 3,
    currentRate: 4,
    technologyList: "FrontEnd",
  },
  {
    courseId: 6,
    lastUpdate: "2023-08-22T05:34:42.901Z",
    tumbImageAddress: nextJs,
    likeCount: 122,
    title: "متخصص NextJS",
    currentRegistrants: 240,
    statusName: "درحال ثبت نام",
    teacherName: "امیرعباس بابائی",
    levelName: "پیشرفته",
    cost: 800_000,
    courseRate: 3,
    currentRate: 4,
    technologyList: "FrontEnd",
  },
  {
    courseId: 7,
    lastUpdate: "2023-10-24T05:34:42.901Z",
    tumbImageAddress: chatGpt,
    likeCount: 72,
    title: "توسعه با ChatGPT",
    currentRegistrants: 163,
    statusName: "درحال ثبت نام",
    teacherName: "امیرعباس بابائی",
    levelName: "پیشرفته",
    cost: 450_000,
    courseRate: 3,
    currentRate: 4,
    technologyList: "Soft Skill",
  },
  {
    courseId: 8,
    lastUpdate: "2024-01-11T05:34:42.901Z",
    tumbImageAddress: webSocket,
    likeCount: 24,
    title: "آموزش WebSocket",
    currentRegistrants: 37,
    statusName: "درحال ثبت نام",
    teacherName: "امیرعباس بابائی",
    levelName: "پیشرفته",
    cost: 100_000,
    courseRate: 2,
    currentRate: 4,
    technologyList: "BackEnd",
  },
  {
    courseId: 9,
    lastUpdate: "2023-07-04T05:34:42.901Z",
    tumbImageAddress: apiNodeJs,
    likeCount: 29,
    title: "API نویسی با NodeJS",
    currentRegistrants: 42,
    statusName: "درحال ثبت نام",
    teacherName: "آرمان رضوانی",
    levelName: "پیشرفته",
    cost: 2_000_000,
    courseRate: 4,
    currentRate: 4,
    technologyList: "BackEnd",
  },
  {
    courseId: 10,
    lastUpdate: "2023-02-11T05:34:42.901Z",
    tumbImageAddress: css,
    likeCount: 442,
    title: "آموزش CSS",
    currentRegistrants: 530,
    statusName: "درحال ثبت نام",
    teacherName: "آرمان رضوانی",
    levelName: "پیشرفته",
    cost:770_000,
    courseRate: 4,
    currentRate: 4,
    technologyList: "FrontEnd",
  },
  {
    courseId: 11,
    lastUpdate: "2023-03-16T05:34:42.901Z",
    tumbImageAddress: html,
    likeCount: 375,
    title: "آموزش HTML",
    currentRegistrants: 423,
    statusName: "درحال برگذاری",
    teacherName: "امیرعباس بابائی",
    levelName: "پیشرفته",
    cost: 600_000,
    courseRate: 3,
    currentRate: 4,
    technologyList: "FrontEnd",
  },
  {
    courseId: 12,
    lastUpdate: "2023-10-22T05:34:42.901Z",
    tumbImageAddress: django,
    likeCount: 12,
    title: "متخصص جنگو",
    currentRegistrants: 25,
    statusName: "درحال برگذاری",
    teacherName: "امیرعباس بابائی",
    levelName: "پیشرفته",
    cost: 2_222_000,
    courseRate: 2,
    currentRate: 4,
    technologyList: "Python",
  },
  {
    courseId: 13,
    lastUpdate: "2023-05-29T05:34:42.901Z",
    tumbImageAddress: jsBlack,
    likeCount: 122,
    title: "جاوا اسکریپت گرایش امنیت",
    currentRegistrants: 211,
    statusName: "درحال برگذاری",
    teacherName: "آرمان رضوانی",
    levelName: "پیشرفته",
    cost: 3_300_000,
    courseRate: 5,
    currentRate: 4,
    technologyList: "JavaScript",
  },
  {
    courseId: 14,
    lastUpdate: "2024-02-16T05:34:42.901Z",
    tumbImageAddress: typeScript,
    likeCount: 234,
    title: "آموزش TypeScript",
    currentRegistrants: 277,
    statusName: "درحال برگذاری",
    teacherName: "امیرعباس بابائی",
    levelName: "پیشرفته",
    cost: 1_050_000,
    courseRate: 3,
    currentRate: 4,
    technologyList: "JavaScript",
  },
  {
    courseId: 15,
    lastUpdate: "2024-02-10T05:34:42.901Z",
    tumbImageAddress: python,
    likeCount: 111,
    title: "متخصص پایتون",
    currentRegistrants: 111,
    statusName: "درحال برگذاری",
    teacherName: "آرمان رضوانی",
    levelName: "پیشرفته",
    cost: 1_111_000,
    courseRate: 5,
    currentRate: 4,
    technologyList: "Python",
  },
  {
    courseId: 16,
    lastUpdate: "2023-03-03T05:34:42.901Z",
    tumbImageAddress: vsCode,
    likeCount: 275,
    title: "آموزش کاربردی VS Code",
    currentRegistrants: 147,
    statusName: "درحال برگذاری",
    teacherName: "آرمان رضوانی",
    levelName: "مبتدی",
    cost: 334_000,
    courseRate: 3,
    currentRate: 4,
    technologyList: "Soft Skill",
  },

  {
    courseId: 17,
    lastUpdate: "2024-01-01T05:34:42.901Z",
    tumbImageAddress: fastHtmlCss,
    likeCount: 61,
    title: "کدنویسی سریع با HTML & CSS",
    currentRegistrants: 99,
    statusName: "درحال برگذاری",
    teacherName: "امیرعباس بابائی",
    levelName: "پیشرفته",
    cost: 400_000,
    courseRate: 2,
    currentRate: 4,
    technologyList: "Soft Skill",
  },
  // {
  //   courseId: 18,
  //   lastUpdate: "2024-02-16T05:34:42.901Z",
  //   tumbImageAddress: SQL,
  //   likeCount: 24,
  //   title: "SQL",
  //   currentRegistrants: 20,
  //   statusName: "درحال برگذاری",
  //   teacherName: "امیرعباس بابائی",
  //   levelName: "پیشرفته",
  //   cost: 2_000_000,
  //   courseRate: 3,
  //   currentRate: 4,
  //   technologyList: "SQL",
  // },
  // {
  //   courseId: 19,
  //   lastUpdate: "2024-02-16T05:34:42.901Z",
  //   tumbImageAddress: Physics,
  //   likeCount: 24,
  //   title: "فیزیک",
  //   currentRegistrants: 20,
  //   statusName: "درحال برگذاری",
  //   teacherName: "امیرعباس بابائی",
  //   levelName: "پیشرفته",
  //   cost: 2_000_000,
  //   courseRate: 3,
  //   currentRate: 4,
  //   technologyList: "Physics",
  // },
  // {
  //   courseId: 20,
  //   lastUpdate: "2024-02-16T05:34:42.901Z",
  //   tumbImageAddress: Physics,
  //   likeCount: 24,
  //   title: "فیزیک",
  //   currentRegistrants: 20,
  //   statusName: "درحال برگذاری",
  //   teacherName: "امیرعباس بابائی",
  //   levelName: "پیشرفته",
  //   cost: 2_000_000,
  //   courseRate: 3,
  //   currentRate: 4,
  //   technologyList: "Physics",
  // },
];